/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.45
 * Generated at: 2025-12-17 13:45:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import com.dongyang.foodpage.dto.FoodDTO;
import java.net.URLEncoder;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(3);
    _jspx_imports_classes.add("com.dongyang.foodpage.dto.FoodDTO");
    _jspx_imports_classes.add("java.net.URLEncoder");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
  
    String mode = (String) request.getAttribute("mode");
    if (mode == null) mode = request.getParameter("mode");
    if (mode == null) mode = "1"; 
    String memberComp = (String) request.getAttribute("memberComp");
    String memberHome = (String) request.getAttribute("memberHome");
    if (memberComp == null) memberComp = "";
    if (memberHome == null) memberHome = "";

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>메인 검색 페이지</title>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"common/style.css?v=2\">\n");
      out.write("<script src=\"");
      out.print(request.getContextPath());
      out.write("/address/addrPopup.js\"></script>\n");
      out.write("<script>\n");
      out.write("function validateDetailSearch(form) {\n");
      out.write("    if (form.start.value.trim() === \"\") {\n");
      out.write("        alert(\"출발지를 입력해주세요.\");\n");
      out.write("        return false;\n");
      out.write("    }\n");
      out.write("    if (form.end.value.trim() === \"\") {\n");
      out.write("        alert(\"도착지를 입력해주세요.\");\n");
      out.write("        return false;\n");
      out.write("    }\n");
      out.write("    // 시간 입력 확인 (경고 후 진행 가능)\n");
      out.write("    if (form.depTime.value.trim() === \"\" || form.eatTime.value.trim() === \"\") {\n");
      out.write("        if (!confirm(\"시간이 입력되어 있지 않습니다. 검색하시겠습니까?\")) {\n");
      out.write("            return false;\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("    if (form.ingredient.value.trim() === \"\") {\n");
      out.write("        alert(\"주재료를 입력해주세요.\");\n");
      out.write("        return false;\n");
      out.write("    }\n");
      out.write("    return true;\n");
      out.write("}\n");
      out.write("\n");
      out.write("function updateTime(type) {\n");
      out.write("    var hour = document.getElementById(type + \"Hour\").value;\n");
      out.write("    var min = document.getElementById(type + \"Min\").value;\n");
      out.write("    \n");
      out.write("    if (hour && min) {\n");
      out.write("        document.getElementsByName(type + \"Time\")[0].value = hour + \":\" + min;\n");
      out.write("    } else {\n");
      out.write("        document.getElementsByName(type + \"Time\")[0].value = \"\";\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/header.jsp", out, false);
      out.write("\n");
      out.write("    <div class=\"page-container\">\n");
      out.write("        <div class=\"sidebar\">\n");
      out.write("            <button onclick=\"location.href='main.do?mode=1'\" class=\"");
      out.print( "1".equals(mode) ? "active" : "" );
      out.write("\">키워드 검색</button>\n");
      out.write("            <button onclick=\"location.href='main.do?mode=2'\" class=\"");
      out.print( "2".equals(mode) ? "active" : "" );
      out.write("\">한상 차림 검색</button>\n");
      out.write("            <button onclick=\"location.href='main.do?mode=3'\" class=\"");
      out.print( "3".equals(mode) ? "active" : "" );
      out.write("\">상세 검색</button>\n");
      out.write("        </div>\n");
      out.write("        <!-- 우측 컨텐츠 영역 -->\n");
      out.write("        <div class=\"content-area\">\n");
      out.write("            ");
 switch(mode) { 
                case "1": // 키워드 검색 
      out.write("\n");
      out.write("                <h2>키워드 검색</h2><p>원하는 음식이나 식당 이름을 입력하세요.</p>\n");
      out.write("                <form action=\"search.do\" method=\"get\"><input type=\"hidden\" name=\"type\" value=\"keyword\">\n");
      out.write("                    <div class=\"form-box-wide\"><ul class=\"search-list\"><li><label>키워드</label><input type=\"text\" name=\"keyword\" placeholder=\"예: 파스타, 스테이크, 마늘, 소고기\"></li></ul>\n");
      out.write("                        <div class=\"search-bar-box\"><button type=\"submit\" style=\"width: 100%;\">검색</button></div>\n");
      out.write("                    </div></form>\n");
      out.write("            ");
  break; case "2": // 한상 차림 검색 
      out.write("\n");
      out.write("                <h2>한상 차림 검색</h2><p>원하는 재료를 입력하면 완벽한 한상을 추천해드립니다. (입력하지 않으면 랜덤 추천)</p>\n");
      out.write("                <form action=\"search.do\" method=\"get\"><input type=\"hidden\" name=\"type\" value=\"simple\">\n");
      out.write("                    <div class=\"form-box-wide\"><ul class=\"search-list\">\n");
      out.write("                            <li><label>주재료 (일품)</label><input type=\"text\" name=\"mainIngredient\" placeholder=\"예: 닭고기, 소고기\"></li>\n");
      out.write("                            <li><label>국&찌개 재료</label><input type=\"text\" name=\"soupIngredient\" placeholder=\"예: 두부, 김치\"></li></ul>\n");
      out.write("                        <div class=\"search-bar-box\"><button type=\"submit\" style=\"width: 100%;\">한상 차림 추천받기</button></div>\n");
      out.write("                    </div></form>\n");
      out.write("            ");
  break; case "3": // 상세 검색 
      out.write("\n");
      out.write("                <h2>상세 검색</h2><p>상황에 딱 맞는 완벽한 메뉴를 찾아드립니다.</p>\n");
      out.write("                <form action=\"search.do\" method=\"get\" onsubmit=\"return validateDetailSearch(this);\"><input type=\"hidden\" name=\"type\" value=\"detail\">\n");
      out.write("                    <div class=\"form-box-wide\"><ul class=\"search-list\">\n");
      out.write("                            <li><label>출발지</label>\n");
      out.write("                                <div class=\"input-wrapper\">\n");
      out.write("                                    <input type=\"text\" id=\"detail_start\" name=\"start\" placeholder=\"서울특별시 구로구 경인로 445\" value=\"");
      out.print( memberComp );
      out.write("\" readonly>\n");
      out.write("                                    <button type=\"button\" onclick=\"openAddrPopup(document.getElementById('detail_start'))\">검색</button>\n");
      out.write("                                </div>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <label>도착지</label>\n");
      out.write("                                <div class=\"input-wrapper\">\n");
      out.write("                                    <input type=\"text\" id=\"detail_end\" name=\"end\" placeholder=\"서울특별시 구로구 가마산로 245\" value=\"");
      out.print( memberHome );
      out.write("\" readonly>\n");
      out.write("                                    <button type=\"button\" onclick=\"openAddrPopup(document.getElementById('detail_end'))\">검색</button>\n");
      out.write("                                </div>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <label>출발 시간</label>\n");
      out.write("                                <div class=\"input-wrapper time-wrapper\" style=\"padding: 0; border: none; background: transparent;\">\n");
      out.write("                                    <input type=\"hidden\" name=\"depTime\">\n");
      out.write("                                    <select id=\"depHour\" onchange=\"updateTime('dep')\" style=\"width: 48%; padding: 8px; border: 1px solid #ddd; border-radius: 4px; margin-right: 4%;\">\n");
      out.write("                                        <option value=\"\">시</option>\n");
      out.write("                                        ");
 for(int i=0; i<24; i++) { String h = String.format("%02d", i); 
      out.write("<option value=\"");
      out.print(h);
      out.write('"');
      out.write('>');
      out.print(h);
      out.write("시</option>");
 } 
      out.write("\n");
      out.write("                                    </select>\n");
      out.write("                                    <select id=\"depMin\" onchange=\"updateTime('dep')\" style=\"width: 48%; padding: 8px; border: 1px solid #ddd; border-radius: 4px;\">\n");
      out.write("                                        <option value=\"\">분</option>\n");
      out.write("                                        ");
 for(int i=0; i<60; i+=5) { String m = String.format("%02d", i); 
      out.write("<option value=\"");
      out.print(m);
      out.write('"');
      out.write('>');
      out.print(m);
      out.write("분</option>");
 } 
      out.write("\n");
      out.write("                                    </select>\n");
      out.write("                                </div>\n");
      out.write("                            </li>\n");
      out.write("                            <li>\n");
      out.write("                                <label>식사 시간</label>\n");
      out.write("                                <div class=\"input-wrapper time-wrapper\" style=\"padding: 0; border: none; background: transparent;\">\n");
      out.write("                                    <input type=\"hidden\" name=\"eatTime\">\n");
      out.write("                                    <select id=\"eatHour\" onchange=\"updateTime('eat')\" style=\"width: 48%; padding: 8px; border: 1px solid #ddd; border-radius: 4px; margin-right: 4%;\">\n");
      out.write("                                        <option value=\"\">시</option>\n");
      out.write("                                        ");
 for(int i=0; i<24; i++) { String h = String.format("%02d", i); 
      out.write("<option value=\"");
      out.print(h);
      out.write('"');
      out.write('>');
      out.print(h);
      out.write("시</option>");
 } 
      out.write("\n");
      out.write("                                    </select>\n");
      out.write("                                    <select id=\"eatMin\" onchange=\"updateTime('eat')\" style=\"width: 48%; padding: 8px; border: 1px solid #ddd; border-radius: 4px;\">\n");
      out.write("                                        <option value=\"\">분</option>\n");
      out.write("                                        ");
 for(int i=0; i<60; i+=5) { String m = String.format("%02d", i); 
      out.write("<option value=\"");
      out.print(m);
      out.write('"');
      out.write('>');
      out.print(m);
      out.write("분</option>");
 } 
      out.write("\n");
      out.write("                                    </select>\n");
      out.write("                                </div>\n");
      out.write("                            </li>\n");
      out.write("                            <li><label>주재료</label><input type=\"text\" name=\"ingredient\" placeholder=\"쌀\"></li></ul>\n");
      out.write("                        <div class=\"search-bar-box\"><button type=\"submit\" style=\"width: 100%;\">상세 조건으로 검색</button></div>\n");
      out.write("                    </div></form>\n");
      out.write("            ");
 break; } 
      out.write("\n");
      out.write("            <!-- 공통 추천 결과 섹션 -->\n");
      out.write("            <section class=\"recommend-section\">\n");
      out.write("                ");
  
                    // [변경] Controller에서 전달된 데이터 사용 (비즈니스 로직 제거됨)
                    List<FoodDTO> resultList = (List<FoodDTO>) request.getAttribute("searchResult");
                    List<Map<String, Object>> hanSangResult = (List<Map<String, Object>>) request.getAttribute("hanSangResult");
                    String searchKeyword = (String) request.getAttribute("searchKeyword");
                    boolean searchFailed = request.getAttribute("searchFailed") != null && (Boolean) request.getAttribute("searchFailed");
                    Integer tempMovetime = (Integer) request.getAttribute("movetime");
                    int movetime = (tempMovetime != null) ? tempMovetime : 0;
                    boolean hasResult = (resultList != null && !resultList.isEmpty() && !searchFailed);
                    boolean hasHanSangResult = (hanSangResult != null && !hanSangResult.isEmpty() && !searchFailed); 
                
      out.write("\n");
      out.write("                <h3>");
 if (hasHanSangResult) { 
      out.write('\'');
      out.print( searchKeyword );
      out.write("' 한상 차림 추천");
 } 
                       else if (hasResult) { if (searchKeyword != null && !searchKeyword.trim().isEmpty() && !"null".equals(searchKeyword)) { 
      out.write('\'');
      out.print( searchKeyword );
      out.write("' 검색 결과");
 } else { 
      out.write("오늘의 추천 메뉴");
 } } 
                       else if (searchFailed) { 
      out.write("검색 결과가 없습니다.");
 } else { 
      out.write("오늘의 추천 메뉴");
 } 
      out.write("</h3>\n");
      out.write("                ");
 if ("3".equals(mode) && movetime > 0) { 
      out.write("<p style=\"font-size: 1.1em; color: #555; margin-top: 10px;\">예상 이동 시간: <strong>");
      out.print( movetime );
      out.write("분</strong></p>");
 } 
      out.write("\n");
      out.write("                <ul class=\"recommend-list\">\n");
      out.write("                ");
 if (hasHanSangResult) {
                      for (Map<String, Object> set : hanSangResult) {
                           List<FoodDTO> menuList = (List<FoodDTO>) set.get("menuList");
                           String totalTime = (String) set.get("totalTime");
                           String setId = (String) set.get("setId");
                           StringBuilder sb = new StringBuilder();
                           for (int i = 0; i < menuList.size(); i++) { sb.append(menuList.get(i).getName()); if (i < menuList.size() - 1) sb.append(","); }
                           String menusParam = URLEncoder.encode(sb.toString(), "UTF-8");
                           
                           String startParam = request.getParameter("start");
                           String endParam = request.getParameter("end");
                           String courseLinkUrl = "courseDetail.do?setId=" + setId + "&menus=" + menusParam;
                           if (startParam != null && !startParam.isEmpty()) courseLinkUrl += "&start=" + URLEncoder.encode(startParam, "UTF-8");
                           if (endParam != null && !endParam.isEmpty()) courseLinkUrl += "&end=" + URLEncoder.encode(endParam, "UTF-8");
                
      out.write("\n");
      out.write("                   <li><a href=\"");
      out.print( courseLinkUrl );
      out.write("\" style=\"text-decoration: none; color: inherit; display: block;\">\n");
      out.write("                            <div class=\"recommend-card\"><div class=\"recommend-content\" style=\"width: 100%; text-align: left; padding: 15px;\">\n");
      out.write("                                    <h4 style=\"margin-bottom: 10px; border-bottom: 1px solid #ddd; padding-bottom: 5px;\">한상 차림 (소요시간: ");
      out.print( totalTime );
      out.write(")</h4>\n");
      out.write("                                    <ul class=\"han-sang-list\">");
 for (FoodDTO food : menuList) { 
      out.write("<li>- ");
      out.print( food.getName() );
      out.write(" </li>");
 } 
      out.write("</ul>\n");
      out.write("                                </div></div></a></li>\n");
      out.write("                ");
 } } else if (hasResult) {                                
                        for (FoodDTO food : resultList) {
                            String startParam = request.getParameter("start");
                            String endParam = request.getParameter("end");
                            String linkUrl = "recipeDetail.do?name=" + URLEncoder.encode(food.getName(), "UTF-8");
                            if (startParam != null && !startParam.isEmpty()) linkUrl += "&start=" + URLEncoder.encode(startParam, "UTF-8");
                            if (endParam != null && !endParam.isEmpty()) linkUrl += "&end=" + URLEncoder.encode(endParam, "UTF-8"); 
      out.write("\n");
      out.write("                    <li><a href=\"");
      out.print( linkUrl );
      out.write("\" style=\"text-decoration: none; color: inherit;\"><div class=\"recommend-card\">\n");
      out.write("                                <div class=\"recommend-content\"><b>");
      out.print( food.getName() );
      out.write("</b><br><span style=\"font-size: 14px; color: #666;\">");
      out.print( food.getTime() );
      out.write("</span></div>\n");
      out.write("                                <div class=\"image-box\"><img src=\"");
      out.print( food.getImg() );
      out.write("\" alt=\"");
      out.print( food.getName() );
      out.write("\" onerror=\"this.src='images/default.jpg'\"></div>\n");
      out.write("                            </div></a></li>\n");
      out.write("                ");
 } } else if (!searchFailed) { 
      out.write("\n");
      out.write("                    <!-- 추천 결과도 없고 실패도 아닌 경우 (로직 오류 방지용) -->\n");
      out.write("                    <li style=\"width: 100%; text-align: center; padding: 30px; color: #666;\">\n");
      out.write("                        <div style=\"font-size: 2em; margin-bottom: 10px;\">🚧</div>\n");
      out.write("                        <div>일시적으로 추천 메뉴를 불러올 수 없습니다.</div>\n");
      out.write("                        <div style=\"font-size: 0.8em; margin-top: 5px;\">잠시 후 다시 시도해주세요.</div>\n");
      out.write("                    </li>\n");
      out.write("                ");
 } else { 
      out.write("\n");
      out.write("                    <li style=\"width: 100%; text-align: center; padding: 30px; color: #666;\">\n");
      out.write("                        <div style=\"font-size: 2em; margin-bottom: 10px;\">🚧</div>\n");
      out.write("                        <div>일시적으로 추천 메뉴를 불러올 수 없습니다.</div>\n");
      out.write("                        <div style=\"font-size: 0.8em; margin-top: 5px;\">잠시 후 다시 시도해주세요.</div>\n");
      out.write("                    </li>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                </ul>\n");
      out.write("            </section>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
