/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.45
 * Generated at: 2025-12-17 13:48:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import com.dongyang.foodpage.dto.MemberDTO;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.dongyang.foodpage.dto.MemberDTO");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

  String role = (String) session.getAttribute("role");
  if (role == null || !"ADMIN".equals(role)) {
    response.sendRedirect(request.getContextPath() + "/member/login.jsp");
    return;
  }
  List<MemberDTO> members = (List<MemberDTO>) request.getAttribute("members");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>회원관리</title>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/common/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"admin-container\">\n");
      out.write("  <div class=\"admin-header\">\n");
      out.write("    <h2>회원 관리 (ADMIN)</h2>\n");
      out.write("    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/mypage.jsp\" style=\"text-decoration: none; color: #555; font-weight: bold;\">← 마이페이지로</a>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <!-- 회원 목록 테이블 -->\n");
      out.write("  <table class=\"data-table\">\n");
      out.write("    <thead>\n");
      out.write("      <tr>\n");
      out.write("        <th>아이디</th>\n");
      out.write("        <th>이름</th>\n");
      out.write("        <th>권한</th>\n");
      out.write("        <th>관리</th>\n");
      out.write("        <th>수정</th>\n");
      out.write("      </tr>\n");
      out.write("    </thead>\n");
      out.write("    <tbody>\n");
      out.write("      ");
 if (members != null && !members.isEmpty()) {
           for (MemberDTO m : members) { 
      out.write("\n");
      out.write("      <tr>\n");
      out.write("        <td>");
      out.print( m.getId() );
      out.write("</td>\n");
      out.write("        <td>");
      out.print( m.getName() );
      out.write("</td>\n");
      out.write("        <td>");
      out.print( m.getRole() );
      out.write("</td>\n");
      out.write("        <td>\n");
      out.write("          ");
 if (!"admin".equals(m.getId()) && !"ADMIN".equals(m.getRole())) { 
      out.write("\n");
      out.write("          <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin.do\" method=\"post\" style=\"display:inline;\" onsubmit=\"return confirm('정말 삭제하시겠습니까?');\">\n");
      out.write("            <input type=\"hidden\" name=\"deleteId\" value=\"");
      out.print( m.getId() );
      out.write("\">\n");
      out.write("            <button type=\"submit\" class =\"btn-del\">삭제</button>\n");
      out.write("      \n");
      out.write("          </form>\n");
      out.write("          ");
 } else { 
      out.write("\n");
      out.write("            <span style=\"color: #999; font-size: 13px;\">보호됨</span>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("        </td>\n");
      out.write("        <td>\n");
      out.write("          ");
 if (!"admin".equals(m.getId()) && !"ADMIN".equals(m.getRole())) { 
      out.write("\n");
      out.write("         <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/editUser.do\" method=\"get\" style=\"display:inline;\">\n");
      out.write("            <input type=\"hidden\" name=\"memberId\" value=\"");
      out.print( m.getId() );
      out.write("\">\n");
      out.write("            <button type=\"submit\" class=\"btn-edit\">수정</button>\n");
      out.write("        </form>\n");
      out.write("    ");
 } else { 
      out.write("\n");
      out.write("        <span style=\"color: #999; font-size: 13px;\">보호됨</span>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("        </td>\n");
      out.write("      </tr>\n");
      out.write("      ");
 } } else { 
      out.write("\n");
      out.write("      <tr>\n");
      out.write("        <td colspan=\"4\" style=\"text-align: center; padding: 30px;\">등록된 회원이 없습니다.</td>\n");
      out.write("      </tr>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("    </tbody>\n");
      out.write("  </table>\n");
      out.write("\n");
      out.write("  <!-- 신규 회원 추가 박스 -->\n");
      out.write("  <div class=\"admin-header\">\n");
      out.write("    <h3>신규 회원 추가</h3>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin.do\" method=\"post\" class=\"add-user-box\">\n");
      out.write("    <input type=\"hidden\" name=\"addMode\" value=\"insert\">\n");
      out.write("    <label>아이디: <input type=\"text\" name=\"id\" required></label>\n");
      out.write("    <label>비밀번호: <input type=\"password\" name=\"pw\" required></label>\n");
      out.write("    <label>이름: <input type=\"text\" name=\"name\" required></label>\n");
      out.write("    <label>권한:\n");
      out.write("      <select name=\"role\">\n");
      out.write("        <option value=\"USER\">USER</option>\n");
      out.write("        <option value=\"ADMIN\">ADMIN</option>\n");
      out.write("      </select>\n");
      out.write("    </label>\n");
      out.write("    <label>알러지: <input type=\"text\" name=\"allergy\"></label>\n");
      out.write("    <label>회사: <input type=\"text\" name=\"comp\"></label>\n");
      out.write("    <label>집주소: <input type=\"text\" name=\"home\"></label>\n");
      out.write("    <button type=\"submit\">회원 추가</button>\n");
      out.write("  </form>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
