/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.45
 * Generated at: 2025-12-14 04:52:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.food;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import com.dongyang.foodpage.dto.*;

public final class recipe_005fdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(7);
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("com.dongyang.foodpage.dto");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>레시피 상세</title>\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/common/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    ");
  List<FoodDTO> courseList = (List<FoodDTO>) request.getAttribute("courseList");
        boolean isCourseMode = (courseList != null && !courseList.isEmpty());
        String outerContainerClass = isCourseMode ? "course-container" : "page-container";
        String contentBoxClass = isCourseMode ? "course-content" : "recipe-detail-container"; 
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"");
      out.print( outerContainerClass );
      out.write("\">\n");
      out.write("        ");
 if (isCourseMode) { 
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "course_sidebar.jsp", out, false);
 } 
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"");
      out.print( contentBoxClass );
      out.write("\">\n");
      out.write("            ");
  FoodDTO food = (FoodDTO) request.getAttribute("food");
                List<RouteResultDTO> routeResults = (List<RouteResultDTO>) request.getAttribute("routeResults");
                List<String> allergyList = (List<String>) request.getAttribute("allergyList");
                List<ParsedIngredientDTO> fridgeList = (List<ParsedIngredientDTO>) request.getAttribute("fridgeList"); 
                
                boolean hasAllergyTrigger = false;
                String detectedAllergies = "";
                if (food != null && allergyList != null && !allergyList.isEmpty()) {
                    List<ParsedIngredientDTO> ings = food.getParsedIngredients();
                    if (ings != null) {
                        for (ParsedIngredientDTO ing : ings) {
                            for (String alg : allergyList) {
                                if (ing.getName().contains(alg)) {
                                    hasAllergyTrigger = true;
                                    if (!detectedAllergies.contains(alg)) detectedAllergies += (detectedAllergies.isEmpty() ? "" : ", ") + alg;
                                }
                            }
                        }
                    }
                }

                if (food != null) { 
      out.write("\n");
      out.write("                <h1 class=\"recipe-title\">");
      out.print( food.getName() );
      out.write("</h1>\n");
      out.write("                ");
 if (hasAllergyTrigger) { 
      out.write("<div class=\"allergy-warning-banner\">&#9888; 주의: 회원님의 알레르기 유발 성분이 포함되어 있습니다! (");
      out.print( detectedAllergies );
      out.write(")</div>");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                <section class=\"route-section\">\n");
      out.write("                    ");
 Map nearestMart = (Map) request.getAttribute("nearestMart");
                       if (nearestMart != null) { 
      out.write("\n");
      out.write("                        <div class=\"mart-recommend-box\">\n");
      out.write("                            <h3 class=\"mart-recommend-title\">&#128722; 추천 경유지: ");
      out.print( (String)nearestMart.get("place_name") );
      out.write("</h3>\n");
      out.write("                            <p style=\"margin: 5px 0; color: #555;\">");
      out.print( (String)nearestMart.get("road_address_name") );
      out.write(" <span style=\"font-size: 0.9em; color: #888;\">(도착지에서 ");
      out.print( (String)nearestMart.get("distance") );
      out.write("m)</span></p>\n");
      out.write("                            \n");
      out.write("                            ");
 
                                // 경유지 구매 목록 로직 추가
                                List<ParsedIngredientDTO> martIngs = food.getParsedIngredients();
                                List<IngredientComparisonDTO> martComps = (List<IngredientComparisonDTO>) request.getAttribute("comparisonList");
                                List<String> martBuyList = new ArrayList<>();

                                if (martIngs != null && martComps != null && martIngs.size() == martComps.size()) {
                                    for (int k = 0; k < martIngs.size(); k++) {
                                        IngredientComparisonDTO mc = martComps.get(k);
                                        // 냉장고에 없거나 부족한 경우 (충분하지 않은 경우)
                                        if (mc != null && !mc.isSufficient()) {
                                            ParsedIngredientDTO mi = martIngs.get(k);
                                            String buyAmountStr = "";
                                            
                                            // 구매 필요량 계산 로직 (아래 재료 섹션 로직과 유사)
                                            if ("냉장고에 없음".equals(mc.getComparisonMessage())) {
                                                buyAmountStr = "구매 필요";
                                            } else {
                                                double buyQty = mc.getRequiredQuantity() - mc.getAvailableQuantity();
                                                if (buyQty > 0) {
                                                    String mUnit = mi.getUnit() != null ? mi.getUnit() : "";
                                                    buyAmountStr = String.format("%.1f%s", buyQty, mUnit);
                                                } else {
                                                    buyAmountStr = "구매 필요";
                                                }
                                            }
                                            martBuyList.add(mi.getName() + "(" + buyAmountStr + ")");
                                        }
                                    }
                                }
                                
                                if (!martBuyList.isEmpty()) {
                            
      out.write("\n");
      out.write("                                <div style=\"margin-top: 10px; padding-top: 10px; border-top: 1px dashed #bbb; font-size: 0.95em;\">\n");
      out.write("                                    <strong style=\"color: #d32f2f;\">🛒 경유지 구매 추천 목록:</strong>\n");
      out.write("                                    <span style=\"color: #444;\">");
      out.print( String.join(", ", martBuyList) );
      out.write("</span>\n");
      out.write("                                </div>\n");
      out.write("                            ");
 } 
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    ");
 } 
                       if (routeResults != null && !routeResults.isEmpty()) {
                           for (int i = 0; i < routeResults.size(); i++) {
                               RouteResultDTO route = routeResults.get(i);
                               String sectionTitle = "이동 경로 안내";
                               if (nearestMart != null && routeResults.size() >= 2) {
                                   if (i == 0) sectionTitle = "구간 1: 출발지 &#10145; " + (String)nearestMart.get("place_name");
                                   else sectionTitle = "구간 2: " + (String)nearestMart.get("place_name") + " &#10145; 도착지";
                               } 
      out.write("\n");
      out.write("                            <h3 style=\"");
      out.print( i > 0 ? "margin-top: 40px;" : "" );
      out.write('"');
      out.write('>');
      out.print( sectionTitle );
      out.write(" (소요시간: ");
      out.print( route.getTotalTime() );
      out.write("분)</h3>\n");
      out.write("                            <div class=\"route-path\">\n");
      out.write("                                <div class=\"route-total-time\">구간 소요 시간: ");
      out.print( route.getTotalTime() );
      out.write("분</div>\n");
      out.write("                                <ul class=\"route-steps\">\n");
      out.write("                                    ");
 for (PathDTO path : route.getPaths()) {
                                            String trafficTypeIcon = "";
                                            String trafficTypeName = "";
                                            switch (path.getTrafficType()) {
                                                case 1: trafficTypeIcon = "&#128642;"; trafficTypeName = "지하철"; break;
                                                case 2: trafficTypeIcon = "&#128652;"; trafficTypeName = "버스"; break;
                                                case 3: trafficTypeIcon = "&#128694;"; trafficTypeName = "도보"; break;
                                                default: trafficTypeIcon = "&#128736;"; trafficTypeName = "기타"; break;
                                            } 
      out.write("\n");
      out.write("                                            <li><span class=\"icon\">");
      out.print( trafficTypeIcon );
      out.write("</span>\n");
      out.write("                                                <div class=\"step-info\"><div class=\"step-time\">");
      out.print( trafficTypeName );
      out.write(':');
      out.write(' ');
      out.print( path.getSectionTime() );
      out.write("분</div>\n");
      out.write("                                                    <div class=\"step-name\">\n");
      out.write("                                                        ");
 if (path.getStartName() != null && !path.getStartName().isEmpty()) out.print(path.getStartName());
                                                           if (path.getEndName() != null && !path.getEndName().isEmpty()) out.print(" &gt; " + path.getEndName());
                                                           if (path.getLaneInfo() != null && !path.getLaneInfo().isEmpty()) out.print(" (" + path.getLaneInfo() + ")"); 
      out.write(" \n");
      out.write("                                                    </div></div></li>\n");
      out.write("                                    ");
 } 
      out.write("\n");
      out.write("                                </ul>\n");
      out.write("                            </div>\n");
      out.write("                    ");
 } } else { 
 } 
      out.write("\n");
      out.write("                </section>\n");
      out.write("                                \n");
      out.write("                <p class=\"recipe-meta\">조리 시간: ");
      out.print( food.getTime() != null ? food.getTime() : "정보 없음" );
      out.write("</p>\n");
      out.write("                <img src=\"");
      out.print( food.getImg() != null && !food.getImg().isEmpty() ? food.getImg() : "../images/default.jpg" );
      out.write("\" alt=\"");
      out.print( food.getName() );
      out.write(" 이미지\" class=\"recipe-image\">\n");
      out.write("\n");
      out.write("                <section class=\"ingredients-section\">\n");
      out.write("                   <div style=\"display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid #eee; margin-top: 30px; margin-bottom: 15px; padding-bottom: 10px;\">\n");
      out.write("                        <h3 style=\"margin: 0; border: none; padding: 0;\">재료 정보 (냉장고 비교)</h3>\n");
      out.write("                        \n");
      out.write("                        <form action=\"fridgeAdd.do\" method=\"post\" onsubmit=\"return confirm('부족한 재료를 일괄 구매(냉장고에 추가)하시겠습니까?');\">\n");
      out.write("                            <input type=\"hidden\" name=\"recipeName\" value=\"");
      out.print( food.getName() );
      out.write("\">\n");
      out.write("                            <button type=\"submit\" class=\"btn-bundle-buy\">\n");
      out.write("                                🛒 일괄 구매 (부족분 채우기)\n");
      out.write("                            </button>\n");
      out.write("                        </form>\n");
      out.write("                    </div>\n");
      out.write("                    ");
 List<ParsedIngredientDTO> parsedIngs = food.getParsedIngredients();
                       List<IngredientComparisonDTO> comparisonList = (List<IngredientComparisonDTO>) request.getAttribute("comparisonList");
                       
                       if (parsedIngs != null && !parsedIngs.isEmpty()) {
                           String lastGroup = "___INIT___";
                           boolean ulOpened = false;

                           for (int i = 0; i < parsedIngs.size(); i++) {
                               ParsedIngredientDTO p = parsedIngs.get(i);
                               
                               // 컨트롤러에서 계산된 비교 결과 가져오기 (순서 동일 가정)
                               IngredientComparisonDTO comp = null;
                               if (comparisonList != null && comparisonList.size() > i) {
                                   comp = comparisonList.get(i);
                               }

                               String currentGroup = p.getGroup();
                               if (currentGroup == null) currentGroup = "재료";

                               if (!currentGroup.equals(lastGroup)) {
                                   if (ulOpened) { 
      out.write(" </ul> ");
 } 
                                   if (!"재료".equals(currentGroup) || i > 0 || (parsedIngs.get(parsedIngs.size()-1).getGroup() != null && !parsedIngs.get(parsedIngs.size()-1).getGroup().equals("재료"))) { 
      out.write("\n");
      out.write("                                    <h4 style=\"margin: 20px 0 10px; color: #444; font-size: 1.1em;\">");
      out.print( currentGroup );
      out.write("</h4>\n");
      out.write("                                ");
 } 
      out.write("\n");
      out.write("                                <ul class=\"parsed-ingredient-list\">\n");
      out.write("                                ");
 ulOpened = true; lastGroup = currentGroup; }

                                String ingName = p.getName();
                                String unit = (p.getUnit() != null) ? p.getUnit() : "";
                                String displayNeed = (p.getQuantity() > 0) ? (p.getQuantity() + unit) : p.getAmount();
                                
                                String statusHtml = "";
                                if (comp != null) {
                                    if (comp.isSufficient()) {
                                        statusHtml = "<span style='color: #1976D2; font-weight: bold;'>충분함</span>";
                                        if (comp.getAvailableQuantity() > 0) {
                                            statusHtml += String.format(" <span style='color: #4CAF50; font-size: 0.9em;'>(보유: %.1f%s)</span>", comp.getAvailableQuantity(), comp.getAvailableUnit());
                                        }
                                    } else if ("냉장고에 없음".equals(comp.getComparisonMessage())) {
                                        statusHtml = "<span style='color: #E53935; font-weight: bold;'>구매 필요</span>";
                                    } else if (comp.getComparisonMessage().contains("단위 불일치")) {
                                         statusHtml = "<span style='color: #FF9800; font-weight: bold;'>단위 불일치</span>";
                                         statusHtml += String.format(" <span style='color: #666; font-size: 0.9em;'>(보유: %.1f%s)</span>", comp.getAvailableQuantity(), comp.getAvailableUnit());
                                    } else {
                                        // 부족한 경우 (구매 필요량 계산)
                                        double buyAmount = comp.getRequiredQuantity() - comp.getAvailableQuantity();
                                        if (buyAmount > 0) {
                                            statusHtml = String.format("<span style='color: #E53935; font-weight: bold;'>구매: %.1f%s</span>", buyAmount, unit);
                                            statusHtml += String.format(" <span style='color: #4CAF50; font-size: 0.9em;'>(보유: %.1f%s)</span>", comp.getAvailableQuantity(), comp.getAvailableUnit());
                                        } else {
                                             statusHtml = "<span style='color: #E53935; font-weight: bold;'>구매 필요</span>";
                                        }
                                    }
                                } else {
                                    // 비회원이거나 비교 정보가 없는 경우 상태 메시지 표시 안 함 (필요량만 표시됨)
                                    statusHtml = "";
                                }
                                
      out.write("\n");
      out.write("                            ");

                                boolean isAllergyItem = false;
                                if (allergyList != null) {
                                    for (String alg : allergyList) {
                                        if (ingName.contains(alg)) {
                                            isAllergyItem = true;
                                            break;
                                        }
                                    }
                                }
                            
      out.write("\n");
      out.write("                            <li class=\"parsed-ingredient-item\" style=\"display: flex; justify-content: space-between; align-items: center; padding: 8px 0; border-bottom: 1px solid #eee; ");
      out.print( isAllergyItem ? "background-color: #ffebee;" : "" );
      out.write("\">\n");
      out.write("                                <div class=\"ing-left\">\n");
      out.write("                                    <span class=\"ing-name\" style=\"font-weight: bold; color: #333;\">\n");
      out.write("                                        ");
      out.print( ingName );
      out.write("\n");
      out.write("                                        ");
 if (isAllergyItem) { 
      out.write("<span class=\"allergy-icon\" title=\"알레르기 주의\">&#9888;</span>");
 } 
      out.write("\n");
      out.write("                                    </span>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"ing-right\" style=\"text-align: right; font-size: 0.9em; display: flex; flex-direction: column; align-items: flex-end;\">\n");
      out.write("                                    <div style=\"margin-bottom: 2px;\"><span style=\"color: #666;\">필요: ");
      out.print( displayNeed );
      out.write("</span></div>\n");
      out.write("                                    <div>");
      out.print( statusHtml );
      out.write("</div>\n");
      out.write("                                </div>\n");
      out.write("                            </li>\n");
      out.write("                        ");
 } if (ulOpened) { 
      out.write(" </ul> ");
 } 
                       } else { 
      out.write("\n");
      out.write("                        <div class=\"ingredients-list\">");
      out.print( food.getIngredients() != null && !food.getIngredients().isEmpty() ? food.getIngredients().replace("\n", "<br>") : "재료 정보가 없습니다." );
      out.write("</div>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                </section>\n");
      out.write("\n");
      out.write("               <section class=\"manuals-section\">\n");
      out.write("                    <h3>조리 과정</h3>\n");
      out.write("                    <ul class=\"manuals-list\">\n");
      out.write("                        ");
 List<String> manuals = food.getManuals();
                           if (manuals != null && !manuals.isEmpty()) {
                               for (int i = 0; i < manuals.size(); i++) { 
      out.write("\n");
      out.write("                                <li><strong>");
      out.print( (i + 1) );
      out.write(".</strong> ");
      out.print( manuals.get(i) );
      out.write("</li>\n");
      out.write("                        ");
 } } else { 
      out.write("<li>조리 과정 정보가 없습니다.</li>");
 } 
      out.write("\n");
      out.write("                    </ul>\n");
      out.write("                    <div style=\"text-align: center; margin-top: 30px; margin-bottom: 20px;\">\n");
      out.write("                        <form action=\"cooking.do\" method=\"post\" onsubmit=\"return confirm('조리를 완료하시겠습니까?\\n냉장고에서 보유 중인 재료들이 자동으로 차감됩니다.');\">\n");
      out.write("                            <input type=\"hidden\" name=\"recipeName\" value=\"");
      out.print( food.getName() );
      out.write("\">\n");
      out.write("                            <button type=\"submit\" class=\"btn-finish-cooking\">👨‍🍳 조리 완료 (재료 차감)</button>\n");
      out.write("                        </form>\n");
      out.write("                    </div>\n");
      out.write("                </section>\n");
      out.write("            ");
 } else { 
      out.write("<p>레시피 정보를 찾을 수 없습니다.</p><button onclick=\"history.back()\">뒤로 가기</button>");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    ");

        String cookingMsg = (String) session.getAttribute("cookingMsg");
        String addMsg = (String) session.getAttribute("addMsg");
        
        String alertMsg = null;
        if (cookingMsg != null) {
            alertMsg = cookingMsg;
            session.removeAttribute("cookingMsg");
        } else if (addMsg != null) {
            alertMsg = addMsg;
            session.removeAttribute("addMsg");
        }
        
        if (alertMsg != null) {
    
      out.write("\n");
      out.write("        <script>\n");
      out.write("            alert(\"");
      out.print( alertMsg );
      out.write("\");\n");
      out.write("        </script>\n");
      out.write("    ");

        }
    
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
