/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.45
 * Generated at: 2025-12-17 13:48:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.member;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class mypage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

  String id = (String) session.getAttribute("id");
  String name = (String) session.getAttribute("name");
  String role = (String) session.getAttribute("role");
  String allergy =(String) session.getAttribute("allergy");
  String comp =(String) session.getAttribute("comp");
  String home =(String) session.getAttribute("home");
  if(allergy == null){
	  allergy = "";
  }
  if(comp == null){
	  comp = "";
  }
  if(home == null){
	  home = "";
  }
  if (id == null) {
    response.sendRedirect(request.getContextPath() + "/member/login.jsp");
    return;
  }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>마이페이지</title>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/common/style.css\">\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/address/addrPopup.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"auth-container\">\n");
      out.write("    <div class=\"auth-box\">\n");
      out.write("        <h2>마이페이지</h2>\n");
      out.write("        \n");
      out.write("        <div class=\"section-title\">내 정보</div>\n");
      out.write("        <div class=\"info-list\">\n");
      out.write("            <p>아이디 <span>");
      out.print( id );
      out.write("</span></p>\n");
      out.write("            <p>이름 <span>");
      out.print( name );
      out.write("</span></p>\n");
      out.write("            <p>권한 <span>");
      out.print( role );
      out.write("</span></p>\n");
      out.write("            <p>알레르기 <span>");
      out.print( allergy );
      out.write("</span></p>\n");
      out.write("            <p>회사주소 <span>");
      out.print( comp );
      out.write("</span></p>\n");
      out.write("            <p>집주소 <span>");
      out.print( home );
      out.write("</span></p>\n");
      out.write("            \n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"divider\"></div>\n");
      out.write("\n");
      out.write("        <div class=\"section-title\">정보 수정</div>\n");
      out.write("        ");
 if ("1".equals(request.getParameter("updated"))) { 
      out.write("\n");
      out.write("            <div style=\"color:green; margin-bottom: 10px;\">정보가 수정되었습니다.</div>\n");
      out.write("        ");
 } else if ("0".equals(request.getParameter("updated"))) { 
      out.write("\n");
      out.write("            <div style=\"color:red; margin-bottom: 10px;\">수정에 실패했습니다.</div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/update.do\" method=\"post\" class=\"auth-form\">\n");
      out.write("            <input type=\"text\" name=\"name\" placeholder=\"새 이름 (변경 시 입력)\">\n");
      out.write("            <input type=\"password\" name=\"pw\" placeholder=\"새 비밀번호 (변경 시 입력)\">\n");
      out.write("            <input type=\"text\" name=\"allergy\" placeholder=\"알레르기정보를 , 를 이용해서 구분하여 입력해주세요\">\n");
      out.write("            <div class=\"input-wrapper\">\n");
      out.write("                <input type=\"text\" id=\"comp_addr\" name=\"comp\" placeholder=\"회사주소 변경\" readonly>\n");
      out.write("                <button type=\"button\" onclick=\"openAddrPopup(document.getElementById('comp_addr'))\">검색</button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"input-wrapper\">\n");
      out.write("                <input type=\"text\" id=\"home_addr\" name=\"home\" placeholder=\"집주소 변경\" readonly>\n");
      out.write("                <button type=\"button\" onclick=\"openAddrPopup(document.getElementById('home_addr'))\">검색</button>\n");
      out.write("            </div>\n");
      out.write("            <button type=\"submit\">수정하기</button>\n");
      out.write("        </form>\n");
      out.write("\n");
      out.write("        ");
 if ("ADMIN".equals(role)) { 
      out.write("\n");
      out.write("            <div class=\"divider\"></div>\n");
      out.write("            <div class=\"auth-links\">\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin.do\" style=\"color: #E07A5F; font-weight: bold;\">[관리자] 회원 관리 페이지로 이동</a>\n");
      out.write("            </div>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        \n");
      out.write("        <div class=\"auth-links\">\n");
      out.write("             <a href=\"logout.jsp\" style=\"color: #999;\">로그아웃</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
