/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.45
 * Generated at: 2025-12-14 13:25:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.common;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class error_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    java.lang.Throwable exception = org.apache.jasper.runtime.JspRuntimeLibrary.getThrowable(request);
    if (exception != null) {
      response.setStatus(jakarta.servlet.http.HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>오류 발생</title>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/common/style.css\">\n");
      out.write("<style>\n");
      out.write("    .error-container {\n");
      out.write("        text-align: center;\n");
      out.write("        padding: 50px;\n");
      out.write("        margin-top: 50px;\n");
      out.write("    }\n");
      out.write("    .error-icon {\n");
      out.write("        font-size: 50px;\n");
      out.write("        color: #ff6b6b;\n");
      out.write("        margin-bottom: 20px;\n");
      out.write("    }\n");
      out.write("    .error-feedback {\n");
      out.write("        margin-top: 30px;\n");
      out.write("        padding: 20px;\n");
      out.write("        background-color: #f9f9f9;\n");
      out.write("        border-radius: 8px;\n");
      out.write("        border: 1px solid #eee;\n");
      out.write("    }\n");
      out.write("    .error-feedback h3 {\n");
      out.write("        color: #333;\n");
      out.write("        margin-bottom: 15px;\n");
      out.write("    }\n");
      out.write("    .error-feedback textarea {\n");
      out.write("        width: 80%;\n");
      out.write("        min-height: 100px;\n");
      out.write("        padding: 10px;\n");
      out.write("        border: 1px solid #ccc;\n");
      out.write("        border-radius: 4px;\n");
      out.write("        resize: vertical;\n");
      out.write("        font-size: 1rem;\n");
      out.write("        box-sizing: border-box; /* 패딩이 너비에 포함되도록 */\n");
      out.write("    }\n");
      out.write("    .error-feedback p.help-text {\n");
      out.write("        font-size: 0.9em;\n");
      out.write("        color: #666;\n");
      out.write("        margin-top: 10px;\n");
      out.write("    }\n");
      out.write("    .btn-home {\n");
      out.write("        display: inline-block;\n");
      out.write("        margin-top: 20px;\n");
      out.write("        padding: 10px 20px;\n");
      out.write("        background-color: #333;\n");
      out.write("        color: white;\n");
      out.write("        text-decoration: none;\n");
      out.write("        border-radius: 5px;\n");
      out.write("    }\n");
      out.write("    .btn-home:hover {\n");
      out.write("        background-color: #555;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/common/header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"error-container\">\n");
      out.write("        <div class=\"error-icon\">⚠️</div>\n");
      out.write("        <h2>죄송합니다. 오류가 발생했습니다.</h2>\n");
      out.write("        <p>요청하신 페이지를 찾을 수 없거나, 시스템에 문제가 발생했습니다.</p>\n");
      out.write("        <p>잠시 후 다시 시도해주세요.</p>\n");
      out.write("        \n");
      out.write("        <div class=\"error-feedback\">\n");
      out.write("            <h3>오류를 해결하는 데 도움을 주세요!</h3>\n");
      out.write("            <p>어떤 상황에서 오류가 발생했는지 알려주시면,<br>더 나은 서비스를 제공하는 데 큰 도움이 됩니다.</p>\n");
      out.write("            <textarea placeholder=\"예: '로그인 후 마이페이지 버튼 클릭 시', 'XX 레시피 검색 중' 등 상세하게 입력해주세요. (입력된 내용은 저장되지 않습니다.)\"></textarea>\n");
      out.write("            <p class=\"help-text\">이 정보는 개발팀에게 전달되어 큰 도움이 됩니다.</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\" class=\"btn-home\">홈으로 돌아가기</a>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
