/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.45
 * Generated at: 2025-12-06 08:35:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import com.dongyang.foodpage.dto.FoodDTO;
import java.net.URLEncoder;
import com.dongyang.foodpage.dto.RouteResultDTO;
import com.dongyang.foodpage.dto.PathDTO;
import java.util.stream.Collectors;

public final class course_005fdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(8);
    _jspx_imports_classes.add("com.dongyang.foodpage.dto.FoodDTO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("com.dongyang.foodpage.dto.PathDTO");
    _jspx_imports_classes.add("com.dongyang.foodpage.dto.RouteResultDTO");
    _jspx_imports_classes.add("java.util.stream.Collectors");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    List<FoodDTO> courseList = (List<FoodDTO>) request.getAttribute("courseList");
    FoodDTO activeFood = (FoodDTO) request.getAttribute("activeFood");
    List<RouteResultDTO> routeResults = (List<RouteResultDTO>) request.getAttribute("routeResults");
    String setId = (String) request.getAttribute("setId");
    if (setId == null) setId = "";
    
    // URL 생성을 위한 전체 메뉴 이름 문자열
    String allMenus = "";
    if (courseList != null) {
        StringBuilder sb = new StringBuilder();
        for (int i=0; i<courseList.size(); i++) {
             sb.append(courseList.get(i).getName());
             if (i < courseList.size() - 1) sb.append(",");
        }
        allMenus = sb.toString();
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>한상 차림 상세 보기</title>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"common/style.css?v=3\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/header.jsp", out, false);
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"course-container\">\n");
      out.write("        <!-- 사이드바: 메뉴 목록 -->\n");
      out.write("        <div class=\"course-sidebar\">\n");
      out.write("            <h3>코스 메뉴 (조리시간순)</h3>\n");
      out.write("            ");
 if (courseList != null) { 
                for (FoodDTO food : courseList) {
                    boolean isActive = activeFood != null && food.getName().equals(activeFood.getName());
            
      out.write("\n");
      out.write("            <a href=\"courseDetail.do?setId=");
      out.print( setId );
      out.write("&menus=");
      out.print( URLEncoder.encode(allMenus, "UTF-8") );
      out.write("&active=");
      out.print( URLEncoder.encode(food.getName(), "UTF-8") );
      out.write("\" \n");
      out.write("               class=\"course-menu-item ");
      out.print( isActive ? "active" : "" );
      out.write("\">\n");
      out.write("                ");
      out.print( food.getName() );
      out.write("\n");
      out.write("                <span class=\"time-badge\">");
      out.print( food.getTime() );
      out.write("</span>\n");
      out.write("            </a>\n");
      out.write("            ");
  } 
               } 
      out.write("\n");
      out.write("            <div style=\"margin-top: 20px; text-align: center;\">\n");
      out.write("                <button onclick=\"location.href='index.jsp?mode=2'\" style=\"padding: 10px 20px; cursor: pointer; background: #555; color: white; border: none; border-radius: 5px;\">다른 한상 찾기</button>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- 메인 컨텐츠: 선택된 레시피 상세 -->\n");
      out.write("        <div class=\"course-content\">\n");
      out.write("            ");
 if (activeFood != null) { 
      out.write("\n");
      out.write("                <h1 class=\"recipe-title\">");
      out.print( activeFood.getName() );
      out.write("</h1>\n");
      out.write("                \n");
      out.write("                <p class=\"recipe-meta\">\n");
      out.write("                    조리 시간: ");
      out.print( activeFood.getTime() );
      out.write(" | \n");
      out.write("                    분류: ");
      out.print( activeFood.getCategory() != null ? activeFood.getCategory() : "기타" );
      out.write("\n");
      out.write("                </p>\n");
      out.write("                \n");
      out.write("                <img src=\"");
      out.print( activeFood.getImg() );
      out.write("\" alt=\"");
      out.print( activeFood.getName() );
      out.write("\" class=\"recipe-image\">\n");
      out.write("\n");
      out.write("                <section class=\"ingredients-section\">\n");
      out.write("                    <h3>재료</h3>\n");
      out.write("                    <div class=\"ingredients-list\">\n");
      out.write("                        ");
      out.print( activeFood.getIngredients() != null ? activeFood.getIngredients().replace("\n", "<br>") : "재료 정보 없음" );
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                </section>\n");
      out.write("\n");
      out.write("                <section class=\"manuals-section\">\n");
      out.write("                    <h3>조리 과정</h3>\n");
      out.write("                    <ul class=\"manuals-list\">\n");
      out.write("                        ");
 
                        if (activeFood.getManuals() != null && !activeFood.getManuals().isEmpty()) {
                            int step = 1;
                            for (String manual : activeFood.getManuals()) {
                        
      out.write("\n");
      out.write("                            <li>\n");
      out.write("                                <strong>");
      out.print( step++ );
      out.write(".</strong> ");
      out.print( manual );
      out.write("\n");
      out.write("                            </li>\n");
      out.write("                        ");
 
                            }
                        } else { 
                        
      out.write("\n");
      out.write("                            <li>조리 과정 정보가 없습니다.</li>\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                    </ul>\n");
      out.write("                </section>\n");
      out.write("                \n");
      out.write("                <section class=\"route-section\">\n");
      out.write("                    <h3>이동 경로 정보</h3>\n");
      out.write("                    ");
 if (routeResults != null && !routeResults.isEmpty()) { 
                        for (RouteResultDTO route : routeResults) {
                    
      out.write("\n");
      out.write("                        <div class=\"route-path\">\n");
      out.write("                            <div class=\"route-total-time\">총 소요 시간: ");
      out.print( route.getTotalTime() );
      out.write("분</div>\n");
      out.write("                            <ul class=\"route-steps\">\n");
      out.write("                                ");
 
                                    if (route.getPaths() != null) {
                                        for (PathDTO path : route.getPaths()) {
                                            String trafficTypeIcon = "";
                                            String trafficTypeName = "";
                                            switch (path.getTrafficType()) {
                                                case 1: trafficTypeIcon = "&#128642;"; trafficTypeName = "지하철"; break;
                                                case 2: trafficTypeIcon = "&#128652;"; trafficTypeName = "버스"; break;
                                                case 3: trafficTypeIcon = "&#128694;"; trafficTypeName = "도보"; break;
                                                default: trafficTypeIcon = "&#128736;"; trafficTypeName = "기타"; break;
                                            }
                                
      out.write("\n");
      out.write("                                    <li>\n");
      out.write("                                        <span class=\"icon\">");
      out.print( trafficTypeIcon );
      out.write("</span>\n");
      out.write("                                        <div class=\"step-info\">\n");
      out.write("                                            <div class=\"step-time\">");
      out.print( trafficTypeName );
      out.write(':');
      out.write(' ');
      out.print( path.getSectionTime() );
      out.write("분</div>\n");
      out.write("                                            <div class=\"step-name\">\n");
      out.write("                                                ");
 
                                                    if (path.getStartName() != null && !path.getStartName().isEmpty()) {
                                                        out.print(path.getStartName());
                                                    }
                                                    if (path.getEndName() != null && !path.getEndName().isEmpty()) {
                                                        out.print(" &gt; " + path.getEndName());
                                                    }
                                                    if (path.getLaneInfo() != null && !path.getLaneInfo().isEmpty()) {
                                                        out.print(" (" + path.getLaneInfo() + ")");
                                                    }
                                                
      out.write("\n");
      out.write("                                            </div>\n");
      out.write("                                        </div>\n");
      out.write("                                    </li>\n");
      out.write("                                ");
      }
                                    }
                                
      out.write("\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                    ");
  }
                    } else { 
      out.write("\n");
      out.write("                        <p>이동 경로 정보가 없습니다.</p>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                </section>\n");
      out.write("\n");
      out.write("            ");
 } else { 
      out.write("\n");
      out.write("                <p>선택된 메뉴 정보가 없습니다.</p>\n");
      out.write("            ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
